grid_map_topic: /grid_map_simple_demo/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
  - name: elevation_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.08
     data_max: -0.16


# point_cloud_topic: "/zed/point_cloud/cloud_registered"
# robot_pose_with_covariance_topic: "/pose"
# robot_pose_cache_size: 500
# map_frame_id: "map"
# source_frame_id: "zed_center"
# robot_base_frame_id: "base_link"
# track_point_frame_id: "map"
# track_point_x: 0.0
# track_point_y: 0.0
# track_point_z: 0.0

point_cloud_topic: "/zed/depth/points"
map_frame_id: "world"
source_frame_id: "quad/zed_viz"
robot_base_frame_id: "quad/base_link"
robot_pose_with_covariance_topic: "/quad/pose"
robot_pose_cache_size: 200
track_point_frame_id: "world"


length_in_x: 30
length_in_y: 30
position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.000009
max_variance: 10000.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
surface_normal_estimation_radius: 0.015
surface_normal_positive_axis: z
