length_in_x: 8
length_in_y: 8
position_x: 0.0
position_y: 0.0
track_point_x: 8
resolution: 0.05
min_variance: 0.000009
max_variance: 1000.0
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
surface_normal_estimation_radius: 0.015
surface_normal_positive_axis: z
min_update_rate: 2
enable_visibility_cleanup: true