# Noiseless ground truth measurements
sensor_processor/type: Perfect
point_cloud_topic: "/zed/point_cloud/cloud_registered"
map_frame_id: "map"
source_frame_id: "map"
robot_base_frame_id: "zed_center"
robot_pose_with_covariance_topic: "/pose"
robot_pose_cache_size: 200
track_point_frame_id: "zed_center"

# point_cloud_topic: "/camera/depth/points"
# map_frame_id: "odom"
# source_frame_id: "base_link"
# robot_base_frame_id: "base_link"
# robot_pose_with_covariance_topic: "/pose"
# robot_pose_cache_size: 200
# track_point_frame_id: "odom"

# sensor_processor/type: Perfect
# point_cloud_topic: "/firefly/vi_sensor/camera_depth/depth/points"
# map_frame_id: "world"
# source_frame_id: "firefly/vi_sensor/base_link"
# robot_base_frame_id: "firefly/base_link"
# robot_pose_with_covariance_topic: "/firefly/ground_truth/pose_with_covariance"
# robot_pose_cache_size: 200
# track_point_frame_id: "firefly/base_link"
